# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import templateselector.fields
import varlet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', varlet.models.URLPathField(blank=True, max_length=2048, unique=True, verbose_name='URL')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('template', templateselector.fields.TemplateField(display_name=templateselector.fields.nice_display_name, help_text='templates may affect the display of this page on the website.', match='^varlet/pages/layouts/.+\\.html$')),
            ],
            options={
                'ordering': ('-modified',),
                'swappable': 'VARLET_PAGE_MODEL',
            },
        ),
    ]
